### ISSUE TITLE
Can't install from Chrome webstore. Error `Could not decode image icon.png` 

### ISSUE THREAD

**Issue by stanleylhs** [TomXV/X-to-Twitter-Redirecter-Extension#1] opened 2024-11-16 16:52 UTC
Can't install from Chrome webstore

could not decode image 'icon.png'

Please replace the icon

Extension can still be installed by zip

**Comment by TomXV** [comment] 2024-11-17 13:16
**Thank you for your issue.**

This is a known issue, and it has already been fixed in version 1.1. However, the current version available on the Chrome Web Store is still v1.0, which is why installation fails.

To provide more details, the issue was caused by two factors:
1. The icon file was in SVG format, which led to decoding errors.
2. The icon sizes were inconsistent. Previously, only a 128px icon was provided, but we have added 48px and 16px icons in a minor update.

The updated version with these fixes is currently under review by the Chrome Web Store. We kindly ask for your patience while the review process is completed. In the meantime, you can manually install the fixed version from the release page.

We apologize for the inconvenience and appreciate your understanding. If you encounter any further issues or have questions, feel free to let us know.

**Closed as completed** 2024-11-19 20:45 UTC
